### ISSUE TITLE
2015/12/17 华软绿蝴蝶大规模完蛋原因分析

### ISSUE THREAD

**Issue by xingrz** [xingrz/SwiftzMac#21]
起因：是 NC 的老师改了登录成功后的提示消息
表现：登录成功后即溢出崩溃

先上样本数据：

```
02 1B 11 2A E9 8C 1F 71 45 31 B1 F0 71 17 A8 AF 92 A7 03 03 01 08 15 31 35 33 34
33 37 37 32 36 32 30 30 30 32 31 31 31 30 32 39 36 05 03 3C 06 03 04 0B 95 CF D6
B7 A2 CF D6 D3 D0 D1 A7 C9 FA CA B9 D3 C3 CB FB C8 CB D5 CA BA C5 C9 CF CD F8 A3
AC CF D6 CC D8 CD A8 D6 AA C8 E7 CF C2 A3 BA D1 A7 C9 FA D1 CF BD FB CA B9 D3 C3
CB FB C8 CB D5 CB BA C5 C9 CF CD F8 A3 AC B2 BB B4 E6 D4 DA C8 CE BA CE C0 ED D3
C9 A3 AC C8 E7 D3 D0 B7 A2 CF D6 A3 AC D1 CF CB E0 B4 A6 C0 ED A1 A3 28 C4 FA BF
C9 D3 C3 C1 F7 C1 BF CE AA 36 35 34 31 2E 30 39 31 20 4D 29 28 C4 FA B5 C4 D3 E0
B6 EE CE AA 30 2E 30 30 20 D4 AA 29 25 1A 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 34 06 00 00 00 00 35 06 00 00 00 00 36 06 5D 34
66 00 37 06 00 00 00 00 38 06 40 42 0F 00 13 14 68 74 74 70 3A 2F 2F 31 37 32 2E
31 36 2E 33 2E 32 37 23 03 01 20 03 00
```

**Comment by xingrz** [comment]
人肉解析数据得知：

1. 数据包实际总长度 283 字节
1. 第 2 字节本应该为该数据包的总长度，却为 `0x1B` 即 27

**Comment by xingrz** [comment]
关于 `0x1B` 长度的解释：

- 改了消息后，整个数据包的长度激增到 283 字节
- 然而安腾的协议里，只有 1 个字节（即第 2 字节）表示包长度，最大值为 255
- 于是 283 即 `100011011` 被截断为 `00011011` 即 `0x1B`

结论：安腾是 `0x2B`

**Comment by xingrz** [comment]
~~异常情况：在内存中 dump 出来的数据（一楼的样本）是 283 字节没错，然而 UDP Socket 里[收到的 `NSData`](https://github.com/xingrz/SwiftzMac/blob/6115b5fd2e6fd2a611e39dbe35ecc2f389300528/SwiftzMac/AmtiumPacket.m#L136) 却只有 278 字节。~~

~~既然内存里已经有完整正确的数据了，这个错误应该不是服务器的问题。猜测是我用的网络请求库的 BUG？~~

这个问题不是问题

**Comment by xingrz** [comment]
根据[协议](https://github.com/xingrz/swiftz-protocal#packet)，数据包中每一个字段的结构是 `字段ID(1字节)` `字段长度(1字节)` `字段内容(变长)`。

因为协议里只用了 1 个字节表示长度，因而当时我用了 [`unsigned char`](https://github.com/xingrz/SwiftzMac/blob/6115b5fd2e6fd2a611e39dbe35ecc2f389300528/SwiftzMac/APMutableParams.m#L35) 作为解析循环中偏移值的变量类型。

而服务器返回的这个巨头婴直接就导致这个偏移量超出了 `unsigned char` 的 `0xFF` 大小，导致溢出错误。

@cygmris 和 @lcatro 将这个变量改成了 `unsigned int` 后问题解决。

**Comment by xingrz** [comment]
此外，假如收到的数据包是不完整的，正好断在字段 ID 之后，那么在循环提取字段的这个[过程](https://github.com/xingrz/SwiftzMac/blob/6115b5fd2e6fd2a611e39dbe35ecc2f389300528/SwiftzMac/APMutableParams.m#L39)里：

```objc
unsigned char length = buffer[offset + 1];
```

`offset + 1` 已经超出了 `buffer` 的长度，也会导致崩溃。

解决办法是将循环条件改为：

```objc
while (offset < sizeof(buffer)) {
    // ....
}
```

**Comment by xingrz** [comment]
感谢 @cygmris @lcatro #22

**Comment by stevennight** [comment]
（自行清空原有内容）

**Comment by xingrz** [comment]
@stevennight 谢谢你的好意。但使用反编译的源码发布我是不认可的。这几天我会处理这个问题。

**Comment by stevennight** [comment]
好的。没想到xingrz大哥你还管这个。 作出反编译这种事不好意思。
